# Build steps common to all platforms

steps:
- script: |
    yarn install
  displayName: 'Install dependencies'

- script: |
    yarn run test:ci
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: test-results/tape.xml
    testRunTitle: 'Test ($(Agent.JobName))'
  condition: succeededOrFailed()
  displayName: 'Publish test results'
